[package]
name = "spano"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.70"
approx = "0.5.1"
clap = { version = "4.1.12", features = ["derive"] }
conv = "0.3.3"
ffmpeg-sidecar = "0.3.3"
image = "0.24.5"
imageproc = "0.23.0"
indicatif = "0.17.3"
itertools = "0.10.5"
nalgebra = "0.32.2"
ndarray = {version="0.15.6", features=["approx", "rayon"]}
ndarray-linalg = { version = "0.16.0", features = ["intel-mkl-static"]}
ndarray-npy = "0.8.1"
nshare = "0.9.0"
num-traits = "0.2.15"
rayon = "1.7.0"
rusttype = "0.9.3"
serde_json = "1.0.95"
splines = "4.2.0"
tempfile = "3.5.0"

[profile.release-with-debug]
inherits = "release"
debug-assertions = true
